name: deploy-container
on:
  push:
    branches:
      - master
    paths:
      - "container/**"
defaults:
  run:
    working-directory: container
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
